### ISSUE TITLE
请求创建 1.16.5 版本分支

### ISSUE THREAD

**Issue by LNatit** [ChloePrime/TacInteractKey#1]
我已将该 Mod 回迁至 1.16.5 版本，请求在该仓库中创建**两个**新分支用于合并对应更新（由于 TaC 0.3.11 版本修改了包名，且 0.3.11 前的版本广泛用于整合包中，因此将该版本独立出来单独作为一个 branch，0.3.11版本单独适配作为持续更新的分支）
[仓库地址](https://github.com/LNatit/TacInteractKey)
期待您的回复，谢谢❤

**Comment by ChloePrime** [comment]
创建了两个新分支
1.16和1.16-tac0.3.11

**Comment by ChloePrime** [comment]
创建了两个分支
1.16 和 1.16-tac0.3.10

**Comment by LNatit** [comment]
我已向对应版本分支提交 PR ，麻烦您抽空审阅一下
