### ISSUE TITLE
[潜在Bug/CAE整合包内使用导致多人联机掉线问题]

### ISSUE THREAD

**Issue by Sorrow-Scarlet** [ChloePrime/TacInteractKey#5]
# 问题
- 非崩溃，但导致掉线
- 疑似渲染问题  

# 过程
1. 加入他人世界
2.  使用tac最新版本的vector(任意武器)瞄准生物实体（周围的生物），按F交互正常显示
3. 击杀对应实体，按F交互正常消失
4. 断线

# 重点信息
- CAE整合包，相关信息及链接：https://www.mcmod.cn/modpack/701.html
- 加入他人的多人游戏
- **1.18.2**
- 前期游戏正常，到前中期开始出现频繁断线（illegal packet recieved）

# LOG
[latest.log](https://github.com/ChloePrime/TacInteractKey/files/14310628/latest.log)

# 吐槽  
不是，为啥会导致illegal packet的问题，有点懵圈，但看到log上写的是tacinteract，interact hint导致，就来发issue了

**Comment by ChloePrime** [comment]
tacinteract和illegal packet是两个不同的报错，
以及最新版pr修了这个bug，但是我还没build，见 [PR#4](https://github.com/ChloePrime/TacInteractKey/pull/4)

**Comment by Sorrow-Scarlet** [comment]
好的

**Comment by ChloePrime** [comment]
> 好的

build了，请下载1.2.4版本
